
{'problem_type': 'binary_classification', 'target_col': 'is_phishing', 'target_size': 2, 'manual_inspection_categorical_cols_idx': [2, 24, 27, 28, 29, 30, 31, 33, 34, 35, 36, 51, 52, 53, 54, 55, 56, 60, 61, 63], 'feats_in_constraints': [0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 37, 38]}
Traceback (most recent call last):
  File "C:\Users\yyyfa\ConstrainedDGM\main_tableGAN.py", line 199, in <module>
    main()
  File "C:\Users\yyyfa\ConstrainedDGM\main_tableGAN.py", line 82, in main
    X_train, (cat_cols, cat_idx), (roundable_idx, round_digits) = read_csv(f"data/{args.use_case}/train_data.csv", args.use_case, dataset_info["manual_inspection_categorical_cols_idx"])
  File "C:\Users\yyyfa\ConstrainedDGM\utils.py", line 110, in read_csv
    data = pd.read_csv(csv_filename)
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\io\parsers\readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\io\common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/url/train_data.csv'
Traceback (most recent call last):
  File "C:\Users\yyyfa\ConstrainedDGM\main_tableGAN.py", line 199, in <module>
    main()
  File "C:\Users\yyyfa\ConstrainedDGM\main_tableGAN.py", line 82, in main
    X_train, (cat_cols, cat_idx), (roundable_idx, round_digits) = read_csv(f"data/{args.use_case}/train_data.csv", args.use_case, dataset_info["manual_inspection_categorical_cols_idx"])
  File "C:\Users\yyyfa\ConstrainedDGM\utils.py", line 110, in read_csv
    data = pd.read_csv(csv_filename)
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\io\parsers\readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "D:\Python\envs\cdgm\lib\site-packages\pandas\io\common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/url/train_data.csv'